import Link from "next/link";
import { ArrowLeft, Landmark, LockKeyhole } from "lucide-react";
import { createRecurringItemAction, deleteRecurringItemAction, deleteTransactionRuleAction, updateFinancialAccountAction } from "@/actions/finance-actions";
import { SimpleFinConnectionForm } from "@/components/app/simplefin-connection-form";
import { SettingsUnlockForm } from "@/components/app/settings-unlock-form";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { formatCurrency } from "@/lib/finance";
import { isSettingsAuthorized, settingsProtectionConfigured } from "@/lib/server/settings-auth";
import { getConnectionSettings } from "@/lib/server/simplefin-service";

export const dynamic = "force-dynamic";

export default async function FinanceSettingsPage() {
  const authorized = await isSettingsAuthorized();
  if (!authorized) return <main className="mx-auto grid min-h-screen max-w-xl place-items-center px-4"><Card className="w-full"><CardHeader><LockKeyhole className="mb-2 size-8" /><CardTitle>Finance settings are locked</CardTitle><CardDescription>Unlock this private area to manage bank credentials and syncing.</CardDescription></CardHeader><CardContent><SettingsUnlockForm /></CardContent></Card></main>;
  const data = await getConnectionSettings();
  return (
    <main className="mx-auto flex min-h-screen w-full max-w-5xl flex-col gap-6 px-4 py-8">
      <div className="flex items-center justify-between"><div><p className="text-sm text-[color:var(--muted-foreground)]">Private setup</p><h1 className="text-3xl font-semibold">Connections</h1></div><Button asChild variant="secondary"><Link href="/finance"><ArrowLeft className="size-4" />Dashboard</Link></Button></div>
      {!settingsProtectionConfigured() ? <div className="rounded-2xl border border-[color:var(--warning)] bg-[color:var(--warning-soft)] p-4 text-sm">Set <code>FINANCE_SETTINGS_PASSWORD</code> before deploying. Settings are unlocked only for local development while it is absent.</div> : null}
      <Card><CardHeader><CardTitle>SimpleFIN Bridge</CardTitle><CardDescription>Read-only balances and transactions. The access URL is encrypted at rest and never sent to the browser.</CardDescription></CardHeader><CardContent><div className="grid gap-6 md:grid-cols-[1fr_280px]"><SimpleFinConnectionForm connected={Boolean(data.connection)} /><div className="rounded-2xl bg-[color:var(--muted)] p-4 text-sm"><p className="font-medium">Status: {data.connection?.syncStatus.toLowerCase() ?? "not connected"}</p><p className="mt-2 text-[color:var(--muted-foreground)]">Last synced: {data.connection?.lastSuccessfulSyncAt?.toLocaleString() ?? "Never"}</p>{data.connection?.lastSyncError ? <p className="mt-2 text-[color:var(--danger)]">{data.connection.lastSyncError}</p> : null}<a className="mt-4 inline-block text-[color:var(--primary)] underline" href="https://bridge.simplefin.org/simplefin/create" target="_blank" rel="noreferrer">Create a SimpleFIN token</a></div></div></CardContent></Card>
      <Card><CardHeader><CardTitle>Tracked accounts</CardTitle><CardDescription>Rename accounts, identify their type, or exclude them from dashboard totals.</CardDescription></CardHeader><CardContent className="grid gap-3">{data.accounts.length === 0 ? <p className="text-sm text-[color:var(--muted-foreground)]">Accounts appear here after connecting.</p> : data.accounts.map((account) => <form action={updateFinancialAccountAction} key={account.id} className="grid gap-3 rounded-2xl border p-4 md:grid-cols-[1fr_180px_auto_auto] md:items-end"><input type="hidden" name="id" value={account.id} /><label className="grid gap-1 text-xs text-[color:var(--muted-foreground)]">Display name<Input name="displayName" defaultValue={account.displayName} /></label><label className="grid gap-1 text-xs text-[color:var(--muted-foreground)]">Type<Select name="accountType" defaultValue={account.accountType}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["CHECKING","SAVINGS","CREDIT_CARD","CASH","OTHER"].map((type) => <SelectItem key={type} value={type}>{type.replaceAll("_", " ")}</SelectItem>)}</SelectContent></Select></label><label className="flex h-10 items-center gap-2 text-sm"><input type="checkbox" name="includeInDashboard" defaultChecked={account.includeInDashboard} />Include</label><div className="flex items-center gap-3"><span className="font-mono text-sm">{formatCurrency(account.currentBalanceCents)}</span><Button size="sm"><Landmark className="size-4" />Save</Button></div></form>)}</CardContent></Card>
      <Card><CardHeader><CardTitle>Recurring plan</CardTitle><CardDescription>Paychecks and required obligations make the safe-to-spend estimate useful and transparent.</CardDescription></CardHeader><CardContent className="grid gap-5"><form action={createRecurringItemAction} className="grid gap-3 md:grid-cols-[1fr_140px_180px_170px_auto_auto] md:items-end"><label className="grid gap-1 text-xs">Name<Input name="name" placeholder="Paycheck or rent" required /></label><label className="grid gap-1 text-xs">Amount<Input name="amount" inputMode="decimal" placeholder="0.00" required /></label><label className="grid gap-1 text-xs">Next date<Input name="nextDueDate" type="date" required /></label><label className="grid gap-1 text-xs">Kind<select name="transactionKind" className="h-10 rounded-xl border bg-[color:var(--input)] px-3 text-sm"><option value="EXPENSE">Expense</option><option value="INCOME">Income / paycheck</option><option value="SAVINGS_TRANSFER">Planned savings</option></select></label><label className="flex h-10 items-center gap-2 text-sm"><input type="checkbox" name="isRequired" defaultChecked />Required</label><Button size="sm">Add</Button></form><div className="grid gap-2">{data.recurringItems.map((item) => <div key={item.id} className="flex items-center justify-between rounded-xl border p-3 text-sm"><div><span className="font-medium">{item.name}</span><span className="ml-2 text-[color:var(--muted-foreground)]">{item.transactionKind.replaceAll("_", " ")} · {item.nextDueDate?.toLocaleDateString() ?? "No date"}</span></div><form action={deleteRecurringItemAction}><input type="hidden" name="id" value={item.id} /><span className="mr-3 font-mono">{formatCurrency(item.amountCents)}</span><Button variant="ghost" size="sm">Remove</Button></form></div>)}</div></CardContent></Card>
      <Card><CardHeader><CardTitle>Transaction rules</CardTitle><CardDescription>Rules run from highest priority to lowest. New exact-match rules can be created while reviewing a transaction.</CardDescription></CardHeader><CardContent className="grid gap-2">{data.rules.map((rule) => <div key={rule.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-3 text-sm"><div><span className="font-medium">{rule.normalizedMerchant ?? rule.matchText}</span><span className="ml-2 text-[color:var(--muted-foreground)]">{rule.matchType.replaceAll("_", " ")} · {rule.transactionKind.replaceAll("_", " ")}{rule.category ? ` · ${rule.category.name}` : ""} · priority {rule.priority}</span></div><form action={deleteTransactionRuleAction}><input type="hidden" name="id" value={rule.id} /><Button variant="ghost" size="sm">Delete</Button></form></div>)}</CardContent></Card>
    </main>
  );
}
